[constants]
weekdays = [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",]
months = [ "N/a", "Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec",]
instruction = """You are helping a student comprehend a passage by asking a few probing questions.  All questions should be one sentence at most.

The first question begins:

"Circle or highlight the section of the passage which ..."

For the second question, supply the student with the definition of a vocabulary word from the passage and instruct them to determine which word matches the definition.  The second question begins:

"What word from the text means... "

For 3rd and last question, ask a question that probes the reader's overall understanding of the passage."""
